/* NBA 2K27 Build Lab — V20.5 Build Intelligence
 * Explainable local optimizer. Uses only embedded tables; unknown 2K internals stay indicative.
 */
(function(){'use strict';
const esc=window.escHtml;
const norm=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
const ALIASES={'3 points':'Three-Point','3pt':'Three-Point','trois points':'Three-Point','mid range':'Mid-Range','midrange':'Mid-Range','mi-distance':'Mid-Range','lancer franc':'Free Throw','layup':'Driving Layup','dunk':'Driving Dunk','dunks':'Driving Dunk','dunk debout':'Standing Dunk','post':'Post Control','passe':'Pass Accuracy','passes':'Pass Accuracy','handle':'Ball Handle','dribble':'Ball Handle','speed with ball':'Speed With Ball','perimeter defense':'Perimeter Defense','defense extérieure':'Perimeter Defense','steal':'Steal','interception':'Steal','block':'Block','contre':'Block','rebond défensif':'Defensive Rebound','rebond offensif':'Offensive Rebound','vitesse':'Speed','agilité':'Agility','force':'Strength','vertical':'Vertical','verticalité':'Vertical','endurance':'Stamina','stamina':'Stamina'};
const STYLE_WORDS=[['Shooter',['shooter','tir','tireur','spacing','3&d','3 and d']],['Slasher',['slasher','dunker','dunk','finisseur','cercle']],['Playmaker',['playmaker','créateur','createur','passeur','handler','dribbleur','meneur']],['Lockdown',['lockdown','défenseur','defenseur','perimeter','3&d','3 and d']],['Big',['big','intérieur','interieur','pivot','center','rebond','rim protector']]];
function heightParse(t){let m=String(t).match(/(?:([5-7])\s*['’]\s*(\d{1,2})|([5-7])\s*pieds\s*(\d{1,2})|(1[,.]\d{2})\s*m\b)/i);if(!m)return null;return m[1]?+m[1]*12+ +m[2]:m[3]?+m[3]*12+ +m[4]:Math.round(parseFloat(m[5].replace(',','.'))*100/2.54)}
function position(t){const n=norm(t);if(/\b(pg|point guard|meneur)\b/.test(n))return'PG';if(/\b(sg|shooting guard|arriere)\b/.test(n))return'SG';if(/\b(sf|ailier|small forward)\b/.test(n))return'SF';if(/\b(pf|ailier fort|power forward)\b/.test(n))return'PF';if(/\b(c|center|pivot|interieur)\b/.test(n))return'C';return null}
function style(t){const n=norm(t);let best=['Équilibré',0];STYLE_WORDS.forEach(([s,ws])=>{const x=ws.reduce((a,w)=>a+(n.includes(norm(w))?1:0),0);if(x>best[1])best=[s,x]});return best[0]}
function constraints(t){const n=norm(t),out=[];Object.entries(ALIASES).forEach(([p,a])=>{const m=n.match(new RegExp('(?:'+p.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+')\\s*(?:a|à|de|>=)?\\s*(?:au moins|minimum|min|plus de|>=|\\+)?\\s*(\\d{2})','i'));if(m)out.push({attr:a,min:+m[1],source:p})});const pairs=[['three-point','Three-Point'],['3pt','Three-Point'],['3 points','Three-Point'],['steal','Steal'],['handle','Ball Handle'],['ball handle','Ball Handle'],['driving dunk','Driving Dunk'],['dunk','Driving Dunk'],['vertical','Vertical'],['speed','Speed'],['strength','Strength'],['block','Block'],['perimeter defense','Perimeter Defense'],['pass accuracy','Pass Accuracy']];pairs.forEach(([p,a])=>{const m=n.match(new RegExp('(\\d{2})\\s*\\+?\\s*'+p.replace(/ /g,'\\s*'),'i'));if(m)out.push({attr:a,min:+m[1],source:p})});const m=new Map();out.forEach(x=>{const old=m.get(x.attr);if(!old||x.min>old.min)m.set(x.attr,x)});return [...m.values()]}
function badgeTargets(t){const defs=window.badgeDefs||[],n=norm(t),out=[];defs.forEach(d=>{const mots=s=>' '+s.replace(/[^a-z0-9]+/g,' ')+' ';if(!n.includes(norm(d.name))&&!(BADGE_FR[d.name]&&mots(n).includes(mots(norm(BADGE_FR[d.name])))))return;let level=2;if(/hall\s*of\s*fame|\bhof\b/.test(n))level=4;else if(/\bor\b|\bgold\b/.test(n))level=3;else if(/argent|silver/.test(n))level=2;else if(/bronze/.test(n))level=1;out.push({badge:d.name,level,req:d.req})});return out}
function badgeReqs(bs){const m=new Map();bs.forEach(b=>(b.req||[]).forEach(q=>{const v=q[b.level];if(typeof v==='number'&&(!m.has(q[0])||v>m.get(q[0]).min))m.set(q[0],{attr:q[0],min:v,source:b.badge})}));return [...m.values()]}
function current(){return typeof ratings==='function'?ratings():{}}
function caps(){return typeof bodyCaps==='function'?bodyCaps():{}}
function cost(r){return typeof simulatedCost==='function'?simulatedCost(r):0}
function profile(s){return typeof optimizerProfile==='function'?optimizerProfile(s):{}}
function targetSet(spec){const m=new Map();[...spec.constraints,...badgeReqs(spec.badges)].forEach(x=>{if(!m.has(x.attr)||x.min>m.get(x.attr).min)m.set(x.attr,x)});return [...m.values()]}
function candidate(spec,variant){const base=current(); let r={...base}; const cp=caps(), prof=profile(spec.style), wanted=targetSet(spec);const desired={};wanted.forEach(t=>desired[t.attr]=Math.min(cp[t.attr]??99,t.min));Object.entries(prof).sort((a,b)=>b[1]-a[1]).forEach(([a,w])=>{if(r[a]!=null)desired[a]=Math.max(desired[a]||0,Math.min(cp[a]??99,r[a]+Math.round(w*(variant===1?2:variant===2?3:1))))});Object.entries(desired).forEach(([a,v])=>{if(r[a]!=null)r[a]=Math.max(r[a],v)});
 const names=Object.keys(r),budget=cost(base)+8;for(let it=0;it<160;it++){let best=null,bs=-Infinity;for(const up of names){if(r[up]>=(cp[up]??99))continue;for(const down of names){if(up===down||r[down]<=25)continue;const tr={...r,[up]:r[up]+1,[down]:r[down]-1};if(cost(tr)>budget)continue;let sc=(prof[up]||0)*2-(prof[down]||0)*.7;wanted.forEach(t=>{const before=r[t.attr]||0,after=tr[t.attr]||0;if(after>=t.min)sc+=4;else sc+=Math.max(-8,-(t.min-after)*.3);if(after>before&&after<t.min)sc+=.15});if(sc>bs){bs=sc;best=tr}}}if(!best)break;r=best}
 wanted.forEach(t=>{if(r[t.attr]!=null)r[t.attr]=Math.max(r[t.attr],Math.min(cp[t.attr]??99,t.min))});return r}
function badgeEval(r){let hit=0;for(const d of window.badgeDefs||[]){if(typeof badgeTier==='function'&&badgeTier(d,r).level>0)hit++}return hit}
function animEval(r,h){return (window.ANIMATIONS||[]).filter(a=>h>=a.minH&&h<=a.maxH&&Object.entries(a.req||{}).every(([k,v])=>(r[k]||0)>=v))}
function takeoverEval(r){return (window.takeoverDefs||[]).filter(x=>(r[x[1]]||0)>=x[2])}
function evaluate(r,s,wanted,badges,h){const hard=wanted.filter(t=>(r[t.attr]||0)>=t.min), bh=badges.filter(b=>{const d=(window.badgeDefs||[]).find(x=>x.name===b.badge);return d&&badgeTier(d,r).level>=b.level}),an=animEval(r,h),to=takeoverEval(r),base=cost(current()),delta=Math.abs(cost(r)-base);const score=Math.max(0,Math.min(100,Math.round((hard.length/(wanted.length||1))*45+(bh.length/(badges.length||1))*20+Math.min(1,an.length/12)*15+Math.min(1,to.length/3)*10+(s==='Équilibré'?10:5)-Math.min(10,delta/4))));return{score,hard,bh,an,to,delta}}
function opportunities(r,h){const list=[];for(const d of window.badgeDefs||[]){const st=badgeTier(d,r);if(st.level>=4)continue;const next=(d.req||[]).map(q=>({attr:q[0],need:q[st.level+1]})).filter(x=>typeof x.need==='number').sort((a,b)=>(a.need-(r[a.attr]||0))-(b.need-(r[b.attr]||0)))[0];if(next){const gap=next.need-(r[next.attr]||0);if(gap>=1&&gap<=5)list.push({type:'badge',name:d.name,attr:next.attr,gap})}}
 for(const a of window.ANIMATIONS||[]){if(h<a.minH||h>a.maxH)continue;const miss=Object.entries(a.req||{}).map(([k,v])=>({attr:k,gap:v-(r[k]||0)})).filter(x=>x.gap>0).sort((x,y)=>x.gap-y.gap);if(miss.length===1&&miss[0].gap<=3)list.push({type:'animation',name:a.name,attr:miss[0].attr,gap:miss[0].gap})}return list.sort((a,b)=>a.gap-b.gap).slice(0,8)}
function report(c){const r=c.r,w=c.wanted,gaps=w.filter(t=>(r[t.attr]||0)<t.min).map(t=>`${t.attr} ${r[t.attr]||0}/${t.min}`), changes=Object.keys(r).map(k=>({attr:k,delta:r[k]-current()[k]})).filter(x=>x.delta).sort((a,b)=>Math.abs(b.delta)-Math.abs(a.delta)).slice(0,8);return{gaps,changes,opportunities:opportunities(r,c.spec.height)}}
function render(spec,cands){const el=document.getElementById('dnaReadout');if(!el)return;const tags=[`Style : ${spec.style}`,`Poste : ${spec.position}`,`Taille : ${heightText(spec.height)}`,...spec.constraints.map(x=>`${x.attr} ≥ ${x.min}`),...spec.badges.map(x=>`${nomBadge(x.badge)} ${['','Bronze','Argent','Or','HOF'][x.level]}`)];el.innerHTML=`<div class="dna-summary"><div><b>BUILD DNA • INTELLIGENCE</b><div class="dna-tags">${tags.map(esc).map(x=>`<span>${x}</span>`).join('')}</div></div><small>${cands.length} scénarios • moteur explicable</small></div><div class="dna-candidates">${cands.map((c,i)=>{const q=report(c),e=c.eval;return `<article class="dna-candidate"><div class="dna-candidate-head"><div><span>SCÉNARIO ${i+1}</span><h3>${esc(c.style)} ${i===0?'— recommandé':''}</h3></div><strong>${e.score}%</strong></div><div class="dna-metrics"><span>🎯 Contraintes <b>${e.hard.length}/${c.wanted.length}</b></span><span>🏆 Badges <b>${e.bh.length}/${c.spec.badges.length||0}</b></span><span>🎬 Animations <b>${e.an.length}</b></span><span>⚡ Takeovers <b>${e.to.length}</b></span></div><div class="dna-explain"><b>Pourquoi ?</b><span>${q.changes.length?q.changes.slice(0,4).map(x=>`${esc(x.attr)} ${x.delta>0?'+':''}${x.delta}`).join(' • '):'Aucun changement nécessaire.'}</span></div>${q.gaps.length?`<div class="dna-warning">⚠️ Contraintes non atteintes : ${q.gaps.map(esc).join(' • ')}</div>`:'<div class="dna-ok">✓ Contraintes prioritaires respectées dans les caps intégrés</div>'}${q.opportunities.length?`<div class="dna-opps"><b>🎯 Prochains gains faciles</b>${q.opportunities.slice(0,4).map(o=>`<span>${esc(o.type==='badge'?nomBadge(o.name):o.name)} : +${o.gap} ${esc(o.attr)}</span>`).join('')}</div>`:''}<div class="dna-actions"><button data-dna-apply="${i}">Utiliser ce build</button><button class="secondary" data-dna-copy="${i}">Copier le rapport</button></div></article>`}).join('')}</div><div class="dna-disclaimer">Données de badges/animations issues des tables embarquées. Les caps, coûts et compromis non publiés officiellement restent indicatifs.</div>`;
 el.querySelectorAll('[data-dna-apply]').forEach(b=>b.onclick=()=>{const c=cands[+b.dataset.dnaApply];Object.keys(c.r).forEach(a=>{const x=inputs.find(i=>i.dataset.name===a);if(x)x.value=c.r[a]});document.getElementById('position').value=c.spec.position;document.getElementById('height').value=c.spec.height;update();document.getElementById('builder')?.scrollIntoView({behavior:'smooth'})});
 el.querySelectorAll('[data-dna-copy]').forEach(b=>b.onclick=()=>{const c=cands[+b.dataset.dnaCopy],q=report(c);navigator.clipboard?.writeText(JSON.stringify({version:'20.5',style:c.style,position:c.spec.position,height:c.spec.height,attributes:c.r,evaluation:{score:c.eval.score,badges:c.eval.bh.length,animations:c.eval.an.length,takeovers:c.eval.to.length},changes:q.changes,gaps:q.gaps,opportunities:q.opportunities},null,2))});}
function run(){const text=document.getElementById('dnaPrompt')?.value.trim();if(!text)return;const spec={style:style(text),position:position(text)||document.getElementById('position')?.value||'SF',height:heightParse(text)||heightInches(),constraints:constraints(text),badges:badgeTargets(text)};const wanted=targetSet(spec);const styles=[spec.style,...['Shooter','Slasher','Playmaker','Lockdown','Big','Équilibré'].filter(x=>x!==spec.style)].slice(0,3);const cands=styles.map((s,i)=>{const r=candidate({...spec,style:s},i+1);const c={r,style:s,spec:{...spec,style:s},wanted,eval:evaluate(r,s,wanted,spec.badges,spec.height)};return c}).sort((a,b)=>b.eval.score-a.eval.score);render(spec,cands)}
window.addEventListener('DOMContentLoaded',()=>{document.getElementById('dnaRun')?.addEventListener('click',run);document.querySelectorAll('[data-dna-example]').forEach(b=>b.addEventListener('click',()=>{const t=document.getElementById('dnaPrompt');t.value=b.dataset.dnaExample;run()}))});
})();
