/* NBA 2K27 Build Lab — verified player reference layer
   Source: 2KRatings NBA 2K27 player pages, checked 2026-09-12.
   These are reference profiles, NOT MyPLAYER templates or official 2K Builder caps.
*/
const PLAYER_REFERENCE_VERSION='2026-09-12';
const PLAYER_REFERENCE_SOURCE='2KRatings';
const PLAYERS_DATA=[
 {id:'stephen-curry-2k27',name:'Stephen Curry',team:'Golden State Warriors',positions:['PG','SG'],height:74,weight:185,wingspan:76,ovr:93,archetype:'Crafty Offensive Engine',axes:{Finition:57,Tir:93,Création:87,Défense:57,Physique:77},attributes:{'Three-Point':99,'Mid-Range':94,'Close Shot':98,'Driving Layup':95,'Driving Dunk':36,'Post Control':35,'Ball Handle':97,'Speed With Ball':83,'Pass Accuracy':89,'Perimeter Defense':69,'Steal':49,'Block':51,'Speed':83,'Agility':84,'Strength':48,'Vertical':73,'Stamina':98},meta:{source:PLAYER_REFERENCE_SOURCE,sourceUrl:'https://www.2kratings.com/stephen-curry',checkedAt:PLAYER_REFERENCE_VERSION,gameVersion:'NBA 2K27',confidence:'VERIFIED_COMMUNITY',notes:'Current NBA 2K27 player page. Category axes are the published 2KRatings category scores.'}},
 {id:'luka-doncic-2k27',name:'Luka Doncic',team:'Los Angeles Lakers',positions:['PG','SG'],height:80,weight:230,wingspan:84,ovr:96,archetype:'Crafty Offensive Engine',axes:{Finition:86,Tir:91,Création:93,Défense:57,Physique:83},attributes:{'Three-Point':92,'Mid-Range':94,'Close Shot':98,'Driving Layup':97,'Driving Dunk':75,'Post Control':87,'Ball Handle':95,'Speed With Ball':83,'Pass Accuracy':95,'Perimeter Defense':59,'Steal':66,'Block':53,'Speed':84,'Agility':77,'Strength':72,'Vertical':79,'Stamina':90},meta:{source:PLAYER_REFERENCE_SOURCE,sourceUrl:'https://www.2kratings.com/luka-doncic',checkedAt:PLAYER_REFERENCE_VERSION,gameVersion:'NBA 2K27',confidence:'VERIFIED_COMMUNITY',notes:'Current NBA 2K27 player page. Category axes are the published 2KRatings category scores.'}},
 {id:'shai-gilgeous-alexander-2k27',name:'Shai Gilgeous-Alexander',team:'Oklahoma City Thunder',positions:['PG','SG'],height:78,weight:195,wingspan:84,ovr:97,archetype:'2-Way Mid-Post Playmaker',axes:{Finition:83,Tir:91,Création:93,Défense:79,Physique:85},attributes:{'Three-Point':82,'Mid-Range':99,'Close Shot':97,'Driving Layup':98,'Driving Dunk':75,'Post Control':86,'Ball Handle':96,'Speed With Ball':87,'Pass Accuracy':97,'Perimeter Defense':86,'Steal':70,'Block':62,'Speed':88,'Agility':86,'Strength':66,'Vertical':85,'Stamina':98},meta:{source:PLAYER_REFERENCE_SOURCE,sourceUrl:'https://www.2kratings.com/shai-gilgeous-alexander',checkedAt:PLAYER_REFERENCE_VERSION,gameVersion:'NBA 2K27',confidence:'VERIFIED_COMMUNITY',notes:'Current NBA 2K27 player page. Category axes are the published 2KRatings category scores.'}},
 {id:'anthony-edwards-2k27',name:'Anthony Edwards',team:'Minnesota Timberwolves',positions:['SG','SF'],height:76,weight:295,wingspan:81,ovr:95,archetype:'2-Way Slashing Iso Sniper',axes:{Finition:84,Tir:90,Création:81,Défense:73,Physique:89},attributes:{'Three-Point':92,'Mid-Range':89,'Close Shot':96,'Driving Layup':97,'Driving Dunk':97,'Post Control':84,'Ball Handle':92,'Speed With Ball':90,'Pass Accuracy':79,'Perimeter Defense':85,'Steal':56,'Block':61,'Speed':94,'Agility':90,'Strength':67,'Vertical':97,'Stamina':97},meta:{source:PLAYER_REFERENCE_SOURCE,sourceUrl:'https://www.2kratings.com/anthony-edwards',checkedAt:PLAYER_REFERENCE_VERSION,gameVersion:'NBA 2K27',confidence:'VERIFIED_COMMUNITY',notes:'Current NBA 2K27 player page. Category axes are the published 2KRatings category scores.'}},
 {id:'jayson-tatum-2k27',name:'Jayson Tatum',team:'Boston Celtics',positions:['PF','SF'],height:80,weight:210,wingspan:83,ovr:93,archetype:'2-Way Bucket Chaser',axes:{Finition:84,Tir:89,Création:80,Défense:75,Physique:84},attributes:{'Three-Point':88,'Mid-Range':91,'Close Shot':90,'Driving Layup':95,'Driving Dunk':89,'Post Control':88,'Ball Handle':86,'Speed With Ball':79,'Pass Accuracy':78,'Perimeter Defense':85,'Steal':63,'Block':37,'Speed':82,'Agility':88,'Strength':71,'Vertical':83,'Stamina':95},meta:{source:PLAYER_REFERENCE_SOURCE,sourceUrl:'https://www.2kratings.com/jayson-tatum',checkedAt:PLAYER_REFERENCE_VERSION,gameVersion:'NBA 2K27',confidence:'VERIFIED_COMMUNITY',notes:'Current NBA 2K27 player page. Category axes are the published 2KRatings category scores.'}}
];
